### ISSUE TITLE
Drupal 9 compatibility

### ISSUE THREAD

**Issue by semseysandor** [civicrm/cv#113]
I tried to install a Drupal 9-based CiviCRM, but it failed:

```
cv core:install --no-interaction --cwd=/civi/dir --lang=en_GB --cms-base-url=https://crm.dev --user=CRM_Admin

Error: Call to undefined method Drupal::entityManager() in phar:///usr/local/bin/cv/src/CmsBootstrap.php on line 269 #0 [internal function]: Civi\Cv\CmsBootstrap->bootDrupal8()
```

`Drupal::entityManager()` was removed in Drupal 9. https://www.drupal.org/project/config_entity_revisions/issues/3196948

So I'm wondering, do `cv` support Drupal 9?

I've a quick-fix which seems to work, and ready to submit a PR, I'm just not sure that it's the best way from an architectural point of view.

**Comment by totten** [comment]
> So I'm wondering, do `cv` support Drupal 9?

I believe some of the test/demo processes use both D9 and `cv`, so *some* parts should be working. But it is quite possible that `cv core:install` is not covered. FWIW, `cv core:install` is notably a bit different from other commands. It uses `CmsBootstrap.php`; most others use `Bootstrap.php` (by default) (*These two follow different processes to achieve the goal of bootstrapping.*)

> I've a quick-fix which seems to work, and ready to submit a PR, I'm just not sure that it's the best way from an architectural point of view.

Do share. :)

I guess the ideal would be if some incantation works on both D8+D9. If not, then maybe something adaptive?

```php
if (is_callable(['Drupal', 'entityManager'])) { /* D8 stuff */ }
else { /* D9 stuff */ }
```

**Comment by demeritcowboy** [comment]
I've never used the `--user` argument with core:install - not sure what it would do differently than without it. You can run core:install without `--user`.

That's not a proper "fix" since yes that function is deprecated, but it works for install.

Noting that other cv commands work fine with `--user` and I use it regularly with drupal 9, which jives with the different bootstrap files mentioned.
