### ISSUE TITLE
Error: Call to undefined method Symfony\Component\Console\Helper\Helper::width()

### ISSUE THREAD

**Issue by calbasi** [civicrm/cv#147]
My install: Drupal 10, CiviCRM 5.60alpha1, php8.1

When executing a test command, like:
`/usr/bin/php8.1 vendor/bin/cv ext:list`

I get this error:

> Using extension feed "https://civicrm.org/extdir/ver=5.60.alpha1|uf=Drupal8|status=stable|ready=ready"
> Error: Call to undefined method Symfony\Component\Console\Helper\Helper::width() in /var/www/clients/client4/web5/web/vendor/symfony/console/Helper/Table.php on line 834 #0 /var/www/clients/client4/web5/web/vendor/symfony/console/Helper/Table.php(815): Symfony\Component\Console\Helper\Table->getCellWidth()
> #1 /var/www/clients/client4/web5/web/vendor/symfony/console/Helper/Table.php(381): Symfony\Component\Console\Helper\Table->calculateColumnsWidth()
> #2 phar:///var/www/clients/client4/web5/web/vendor/bin/cv/src/Util/StructuredOutputTrait.php(191): Symfony\Component\Console\Helper\Table->render()
> #3 phar:///var/www/clients/client4/web5/web/vendor/bin/cv/src/Command/ExtensionListCommand.php(84): Civi\Cv\Command\ExtensionListCommand->sendTable()
> #4 phar:///var/www/clients/client4/web5/web/vendor/bin/cv/vendor/symfony/console/Command/Command.php(255): Civi\Cv\Command\ExtensionListCommand->execute()
> #5 phar:///var/www/clients/client4/web5/web/vendor/bin/cv/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
> #6 phar:///var/www/clients/client4/web5/web/vendor/bin/cv/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
> #7 phar:///var/www/clients/client4/web5/web/vendor/bin/cv/src/Application.php(82): Symfony\Component\Console\Application->doRun()
> #8 phar:///var/www/clients/client4/web5/web/vendor/bin/cv/vendor/symfony/console/Application.php(149): Civi\Cv\Application->doRun()
> #9 phar:///var/www/clients/client4/web5/web/vendor/bin/cv/src/Application.php(49): Symfony\Component\Console\Application->run()
> #10 phar:///var/www/clients/client4/web5/web/vendor/bin/cv/bin/cv(27): Civi\Cv\Application::main()
> #11 /var/www/clients/client4/web5/web/vendor/bin/cv(14): require('...')
> #12 {main}
> Error: Call to undefined method Symfony\Component\Console\Helper\Helper::width() in Symfony\Component\Console\Helper\Table->getCellWidth() (line 834 of /var/www/clients/client4/web5/web/vendor/symfony/console/Helper/Table.php).
>

**Comment by totten** [comment]
Thanks for reporting @calbasi.

That sounds like a conflict which isn't supposed to happen. `cv.phar` is supposed to prefix the namespaces of any `Symfony` classes to prevent conflicts, but I inspected the file and - sure enough - the prefixes are missing from those classes. I'm not exactly sure when/why it regressed.

In any event, I'm adding a test to prevent that from happening again -- and re-tuning some "php-scoper" rules.

**Comment by totten** [comment]
@calbasi I've published v0.3.35 to address the namespacing problem indicated above. However, I don't actually have a D10 build handy, so it would it be great if you could test it.

**Comment by totten** [comment]
Correction: v0.3.37 is better than v0.3.35.

**Comment by totten** [comment]
Well, in principle, that should've been resolved by the php-scoper fixes. Feel free to reopen if it's still an issue.
