### ISSUE TITLE
include_path has a 4096 char (minus "__DIR__:") limit in some cases

### ISSUE THREAD

**Issue by bwbroersma** [civicrm/cv#23]
I'm having problem running `civix` and `cv ev` with `include_paths` of more than 4067 chars.
First make a file `needle.php` by running `touch /tmp/needle.php`.
```$ strace -e trace=lstat php5 $(which cv) ev "set_include_path('/' . str_repeat('x', 4062) . ':/tmp');var_dump(stream_resolve_include_path('needle.php'));" 2>&1 | grep /tm```
This results in php looking for `/tm` instead of `/tmp`:
```lstat("/tm/needle.php", 0x7ffcbba82680) = -1 ENOENT (No such file or directory)```

Note that running `cv scr` this file is working:
```<?php set_include_path('/' . str_repeat('x', 4062) . ':/tmp');var_dump(stream_resolve_include_path('needle.php'));```
Does result in:
```string(15) "/tmp/needle.php"```

The `include_path` is long because I have a lot of civicrm modules, and not running this directly in a folder that has a short path . Any clue what's happening here?

**Edit:** updated code to use $(which cv)

**Comment by totten** [comment]
That's pretty wild. I'm able to see the same thing (Ubuntu 16.10, PHP 5.6).

A few other data-points:
 * The full path of `cv` might differ on other systems. Had to change `/usr/local/bin/cv` to `which cv`.
 * There are a few ways to run a PHP snippet from CLI. Interesting to compare:
   * `cv ev` -- fails
   * `wp eval` -- fails
   * `php -r` -- succeeds
   * `drush ev` -- succeeds
 * The same problem occurs with `cv ev` on Drupal 7 and WordPress. 
 * In case it was an issue with `eval()`, I tried [combining `cv scr` and `eval()`](https://gist.github.com/totten/40904453034ff93fcb458e25236a5cc0). But that succeeds.

**Comment by bwbroersma** [comment]
Sorry, forgot to include I also tested `php5 -r` and `cr scr` with `eval`, but forgot in include them because they succeeded, also `cv ev` with an `eval` still fails. I'm on Debian 9 with PHP 5.6.30-0+deb8u1, Drupal 7 and CiviCRM 4.6.22.

The thing I forgot to test: `cv ev` with 'require', this **works** again! (also a `require` with `eval` inside it).

I did a diff of `phpinfo()` to look for differences, that I could not find. Then I looked at how the path stuff works in PHP and found out that the current dir is always included https://github.com/php/php-src/blob/php-5.6.30/main/fopen_wrappers.c#L565 , that is one is different the `__DIR__`, in phar code like `cv` is (for me): `"phar:///usr/local/bin/cv/src/Command"`, so a streaming path instead of a normal path, if we `require` a file, the `__DIR__` is set to the folder of the required file, and everything works again. So maybe other code discover code is run if our local root is `phar://`?

BTW I'm not particularly interested in getting `cv ev` to work, but I do want to get my `civix` working without tricks (and preferably without the need to ignore errors, because it's against my nature ;), because it cannot find `api/class.api.php` (now I solved it by mounting the directory in a shorter path to stay below 4067, and also find out creating the module in a clean drupal/civicrm and then symlinking the extension will work, since it then finds the clean civi with the shorter include_path as root). I noticed the problem (with `strace`) that `lstat` was run on cut off paths. Although I think I *could* just ignore the `api/class.api.php` runtime exception, since it can actually create modules just fine.

**Comment by bwbroersma** [comment]
Ok, I installed the latest `cv` from git and compared calling the phar version versus just running the php code:
```
/some/long/path/www/sites/default/modules/extensions $ php5 ~/builds-from-source/cv/bin/cv ev "set_include_path('/' . str_repeat('x', 4062) . ':/tmp');var_dump(stream_resolve_include_path('needle.php'));"
string(15) "/tmp/needle.php"

/some/long/path/www/sites/default/modules/extensions $ php5 ~/builds-from-source/cv/bin/cv.phar ev "set_include_path('/' . str_repeat('x', 4062) . ':/tmp');var_dump(stream_resolve_include_path('needle.php'));" 
bool(false)
```

So now look why the phar variant doesn't work, I will look into phar & box.

**Comment by bwbroersma** [comment]
It's definitely a phar/box resolving problem, the limit is 4096 (4K like expected), including the `__DIR__` and `:` separator:
This is a minimal example, a file `bin/main`:
`<?php eval("const TMP='/tmp', ROOT='/'; set_include_path(ROOT . str_repeat('x', (1 << 12) - strlen(__DIR__ . PATH_SEPARATOR . ROOT . PATH_SEPARATOR . TMP) + 1) . PATH_SEPARATOR . TMP); var_dump(stream_resolve_include_path('needle.php'));");`
The `+ 1` is the thing that is making it 4097 bytes, so `/tmp` becomes `/tm` on a `fread(*, 4096)`.
with the following `box.json`: `{"main":"bin/main","output":"subpath.phar","stub":true}`
will reproduce the problem, but if the eval is in the root path (e.g. a `box.json` with `{"main":"main","output":"rootpath.phar","stub":true}`), the problem is non-existing.

**Comment by bwbroersma** [comment]
I think it's because of this:

> [ext/opcache/ZendAccelerator.h](https://github.com/php/php-src/blob/15dda5a357f0eff35e73ca18c9380e9bcc3f345f/ext/opcache/ZendAccelerator.h#L84) line 84 [master]:
> ```# define MAXPATHLEN 4096```
>
> [/ext/phar/util.c](https://github.com/php/php-src/blob/f2d4205cfabe8c951258584bfd60a71c5651b472/ext/phar/util.c#L312-L314) line 312-314 [master]:
> ```c
> spprintf(&path, MAXPATHLEN, "phar://%s/%s%c%s", arch, PHAR_G(cwd), DEFAULT_DIR_SEPARATOR, PG(include_path));
> efree(arch);
> ret = php_resolve_path(filename, filename_len, path);
> ```
I'll try to fix it upstream at the official PHP repo.

**Comment by totten** [comment]
@bwbroersma, thanks for sharing -- that's a fascinating investigation. I hope it works out with upstream.
