### ISSUE TITLE
User not set - Joomla

### ISSUE THREAD

**Issue by aydun** [civicrm/cv#40]
On Joomla 3.8.7, Civi 5.1.2, cv v0.2.4-1-g8cd12e4

`$ cv --user=userX ev 'print_r(JFactory::getUser())'`
Should return details of userX but always returns the guest user.

If userX is invalid, an error is correctly returned.

The problem was noted trying to run `cv api --user=userX Job.process_mailing`

**Comment by agh1** [comment]
This may or may not be a `cv` problem.  See [dev/joomla#6](https://lab.civicrm.org/dev/joomla/issues/6).
