### ISSUE TITLE
 [RuntimeException] Cannot resolve path using "cms.root.url"

### ISSUE THREAD

**Issue by adixon** [civicrm/cv#48]
Drupal 8.7.4, CivICRM 5.15.0, cv version v0.2.20, Civi/Drupal installed using the roundearth method with the document root in /var/www/drupal/web

I see Jon's patch in there, and it's finding a lot of good stuff, but seems to get lost finding this specific path variable.

<pre>sudo -u www-data cv -vvv --cwd=/var/www/drupal/ ext:list       
[BootTrait] Start
[BootTrait] Attempting to set verbose error reporting
[BootTrait] Call standard cv bootstrap
[Bootstrap] Options: {
    "dynamicSettingsFile": "phar:///usr/local/bin/cv/settings_location.php",
    "env": "CIVICRM_SETTINGS",
    "prefetch": true,
    "settingsFile": null,
    "search": true,
    "cmsType": null,
    "httpHost": "",
    "output": {}
}
[Bootstrap] Find settings file
[Bootstrap] Load supplemental configuration for "/var/www/drupal/web/sites/default/civicrm.settings.php"
[Bootstrap] Load settings file "/var/www/drupal/web/sites/default/civicrm.settings.php"
[Bootstrap] Find CMS root for "/var/www/drupal"
[Bootstrap] Found "drupal" in "/var/www/drupal/web"
[Bootstrap] Simulate web environment in CLI
[Bootstrap] Initialize class loader
[Bootstrap] Call core bootstrap

                                            
  [RuntimeException]                        
  Cannot resolve path using "cms.root.url"  
                                            

Exception trace:
 () at /var/www/drupal/vendor/civicrm/civicrm-core/Civi/Core/Paths.php:123
 Civi\Core\Paths->getVariable() at /var/www/drupal/vendor/civicrm/civicrm-core/Civi/Core/Paths.php:195
 Civi\Core\Paths->getUrl() at /var/www/drupal/vendor/civicrm/civicrm-core/CRM/Core/Config/MagicMerge.php:272
 CRM_Core_Config_MagicMerge->__get() at /var/www/drupal/vendor/civicrm/civicrm-core/CRM/Extension/System.php:102
 CRM_Extension_System->__construct() at /var/www/drupal/vendor/civicrm/civicrm-core/CRM/Extension/System.php:77
 CRM_Extension_System::singleton() at /var/www/drupal/vendor/civicrm/civicrm-core/Civi/Core/Container.php:496
 Civi\Core\Container::boot() at /var/www/drupal/vendor/civicrm/civicrm-core/CRM/Core/Config.php:113
 CRM_Core_Config::singleton() at phar:///usr/local/bin/cv/src/Bootstrap.php:195
 Civi\Cv\Bootstrap->boot() at phar:///usr/local/bin/cv/src/Util/BootTrait.php:93
 Civi\Cv\Command\BaseExtensionCommand->_boot_full() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/cv/src/Util/BootTrait.php:39
 Civi\Cv\Command\BaseExtensionCommand->boot() at phar:///usr/local/bin/cv/src/Command/ExtensionListCommand.php:63
 Civi\Cv\Command\ExtensionListCommand->execute() at phar:///usr/local/bin/cv/vendor/symfony/console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/cv/vendor/symfony/console/Application.php:850
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/cv/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/cv/src/Application.php:46
 Civi\Cv\Application->doRun() at phar:///usr/local/bin/cv/vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/cv/src/Application.php:15
 Civi\Cv\Application::main() at phar:///usr/local/bin/cv/bin/cv:26
 require() at /usr/local/bin/cv:10
</pre>

**Comment by mlutfy** [comment]
Hi Alan,

I think this is the same issue as this one reported by Jon yesterday:

* https://lab.civicrm.org/dev/drupal/issues/75
* https://github.com/civicrm/civicrm-core/pull/14775

**Comment by adixon** [comment]
Confirmed, your patch below fixes. Thanks!

https://github.com/civicrm/civicrm-core/pull/14772
