### ISSUE TITLE
Joomla: [TYPO3\PharStreamWrapper\Exception]  

### ISSUE THREAD

**Issue by kainuk** [civicrm/cv#49]
Running a cv command (e.g `cv sql`) on a CiviCRM 5.17.0 /Joomla 3.9.11 installation throws the following exception:

     [TYPO3\PharStreamWrapper\Exception]                                                                              
     Unexpected file extension in "phar:///home/klaas/buildkit/bin/cv/vendor/composer/../../src/Util/Datasource.php" 

I use the standard cv phar file from buildkit (v0.2.19)

When unpack `cv`  on the file system, it works fine.

**Comment by kainuk** [comment]
`drush` had a comparable problem, see https://www.drupal.org/project/drupal/issues/3026386#comment-12929380 . The solution was to patch the code of drupal, instead the code of drush. So I think the error is caused by some new security policy in Joomla, that cannot be fixed in the `cv` code.

**Comment by totten** [comment]
Resolved via #122.
