### ISSUE TITLE
Deprecated: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by adixon** [civicrm/cv#91]
Using php 7.4.14, cv v0.3.5, CiviCRM 5.34.0

I'm using cv to run system jobs, but it's failing because php deprecation notices are getting in the way.

<code>Deprecated: Array and string offset access syntax with curly braces is deprecated in /path/to/extensionname.civix.php</code>

Specifically, I'm using this:

<code>cv --out=list api User.get return="name" id=1</code>

It's supposed to spit out the drupal user 1, so that I can run the system job with that user, but now that result is cluttered with those deprecation notices.

In this case, those deprecation notices are all from extension civix boilerplate files.

Of course, fixing all the extensions would the responsible thing to do, but it's curious to me why these notices are suddenly appearing.

Changing the php error_reporting does not seem to make a difference - it's not clear to me whether it's being overridden in some php code somewhere, or what ....

I should also say, this doesn't show up for civi 5.28.4, so it's not really a cv bug, but what it showed up is the inability to get the nice out=list when php errors are getting output.

**Comment by totten** [comment]
> Of course, fixing all the extensions would the responsible thing to do, but it's curious to me why these notices are suddenly appearing.

Right

> Changing the php error_reporting does not seem to make a difference - it's not clear to me whether it's being overridden in some php code somewhere, or what ....

Right, the challenge is that `cv` is deferential about several aspects of error reporting -- so it can be hard to tell if the policy change was something in civicrm-core config/version, the CMS config/version, PHP config/version, or cv config/version (or some dependency for one of those -- like `symfony/console`).

> I should also say, this doesn't show up for civi 5.28.4, so it's not really a cv bug, but what it showed up is the inability to get the nice out=list when php errors are getting output.

Does that mean that warnings are hitting STDOUT instead of STDERR?

Maybe that's actually a good argument for being less deferential about the error handler.

For context, I've always assumed that we boot the CMS and then let it define the default error-handler. But goodness only knows the overall effect when 6+ parties have the opportunity to replace the default error handler, and when almost all of them are optimized for web-based requests.

So perhaps `cv` should:
* Define an error-handler which prints to STDERR. (Maybe throw in some color coding...)
* Replace the default error handler at a couple strategic points (eg when starting `Application::main()` and then again after booting in `BootTrait::boot()`)

**Comment by adixon** [comment]
> > I should also say, this doesn't show up for civi 5.28.4, so it's not really a cv bug, but what it showed up is the inability to get the nice out=list when php errors are getting output.
> 
> Does that mean that warnings are hitting STDOUT instead of STDERR?

I think the answer is yes, i.e.:

cv --out=list api User.get return="name" id=1 2>/dev/null

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/drupal/web/sites/default/files/civicrm/ext/org.civicrm.angularprofiles/angularprofiles.civix.php on line 246

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/drupal/web/sites/default/files/civicrm/ext/civivolunteer/volunteer.civix.php on line 246

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/drupal/web/sites/default/files/civicrm/ext/exportui/exportui.civix.php on line 246

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/drupal/web/sites/default/files/civicrm/ext/civisualize/civisualize.civix.php on line 247

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/drupal/web/sites/default/files/civicrm/ext/org.civicrm.shoreditch/shoreditch.civix.php on line 246

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/drupal/web/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/mosaico.civix.php on line 247

**Comment by adixon** [comment]
> Maybe that's actually a good argument for being less deferential about the error handler.
> 
> For context, I've always assumed that we boot the CMS and then let it define the default error-handler. But goodness only knows the overall effect when 6+ parties have the opportunity to replace the default error handler, and when almost all of them are optimized for web-based requests.
> 
> So perhaps `cv` should:
> 
> * Define an error-handler which prints to STDERR. (Maybe throw in some color coding...)
> * Replace the default error handler at a couple strategic points (eg when starting `Application::main()` and then again after booting in `BootTrait::boot()`)

Thanks for the explanation and agreed with the diagnosis and conclusion.

But I can also see why it's non-trivial, and that your existing strategy has merit for a few reasons.

And finally, it shows me the risks of my workaround to the requirement of using --user for authentication of the api call in cv, which is probably worth figuring out more directly.

I'll close this issue, thanks again for the help.

**Comment by adixon** [comment]
I manually updated the referenced civix code as per my PR for civix:

https://github.com/totten/civix/pull/207

And the deprecation warnings have disappeared.

So, that is one way in which my specific need is solved, but leaves open the question of why it started - it suggests that perhaps civicrm core has changed some strategy in error reporting.

Also interesting is that the deprecation warning was getting triggered without that code being executed, presumably it was during the opcache generation phase (I'm probably oversimplifying).

In any case, cleaning up old code in civix is a good outcome.

It also suggests we'll have some other issues arising with civicrm 5.34.0 related to changes in error reporting.
