### ISSUE TITLE
How create a fresh DB install 

### ISSUE THREAD

**Issue by weedkiller** [civicrm/cv#98]
Hello can you please share some information on the CLI to create a fresh CRM install.

**Comment by MegaphoneJon** [comment]
What CMS are you using?  I generally use this:

```
cv -n core:install --db=mysql://{{ db_user }}:{{ password }}@localhost/{{ crm_db_name }} --cms-base-url={{ primary_url }}
```

However, with Drupal 8, you just do it from `composer`.

**Comment by weedkiller** [comment]
I want to install without a DB, we are testing some errors and wanted to trouble shoot and report it from my desktop

But I dont know how to create an empty DB

**Comment by MegaphoneJon** [comment]
I'm not sure what's meant by an "empty" db here.  CiviCRM ships with various settings in its database, and won't function without those.  If by "empty" you mean "as if I installed CiviCRM successfully but have done nothing else", the instructions I gave should suffice.

**Comment by weedkiller** [comment]
i was unable to create it, I am close this.

it would be nice to have a simpler easier straight forward sql to run from the db
